name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Lint bash scripts
        run: |
          shopt -s globstar nullglob
          for f in **/*.sh; do
            echo "shellcheck $f"
            shellcheck "$f"
          done
      - name: Validate YAML files
        run: |
          python - <<'PY'
          import glob, yaml, sys
          ok=True
          for f in glob.glob("**/*.yml", recursive=True)+glob.glob("**/*.yaml", recursive=True):
              try:
                  yaml.safe_load(open(f))
                  print("OK", f)
              except Exception as e:
                  print("BAD", f, e); ok=False
          sys.exit(0 if ok else 1)
          PY
